//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Users : BaseViewModel
    {
        public int Id { get; set; }

        private string _DisplayName;
        public string DisplayName
        {
            get { return _DisplayName; }
            set
            {
                _DisplayName = value
                    ; OnPropetyChange();
            }
        }

        private string _UserName;
        public string UserName { get { return _UserName; } set { _UserName = value; OnPropetyChange(); } }

        public string Password { get; set; }
        public string QRCode { get; set; }
        public string BarCode { get; set; }
        public int IdRole { get; set; }

        public virtual UsersRole UsersRole { get; set; }
    }
}
